service: bambee-tasks-service
provider:
  name: aws
  runtime: nodejs12.x
  stage: develop
  environment:
    API_IDENTIFIER: ${ssm:API_IDENTIFIER}
    AUTH_DOMAIN: ${ssm:AUTH_DOMAIN}
    JWKS_URI: ${ssm:JWKS_URI}
    MONGODB_URI: ${ssm:MONGODB_URI}
    clientId: ${ssm:clientId}
  region: us-west-2
functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
